import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useKeplr } from "@/services/keplr";
import { useWallet } from "@/context/wallet";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const keplr = useKeplr();
  const wallet = useWallet();

  const ConnectWallet = () => {
    if (wallet.initialized) {
      keplr.disconnect();
    } else {
      keplr.connect();
    }
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <button onClick={ConnectWallet}>
          {wallet.address ? "Disconnect" : "Connect"}
        </button>
      </main>
    </>
  );
}
